#!/usr/bin/env python3
"""Rewrite projects.json from the bundles actually present.

Each bundle is generated by its own job, so each carries a projects.json listing only itself. When the bundles
are merged for publication that file has to be rebuilt from what is there, or one library's entry overwrites the
other's and the switcher shows a single name.

    python3 tools/rebuild_projects.py site/data
"""
import json
import pathlib
import sys


def main(root: pathlib.Path) -> None:
    entries = []
    for manifest in sorted(root.glob("*/manifest.json")):
        m = json.loads(manifest.read_text())
        entries.append({
            "slug": m.get("slug", manifest.parent.name),
            "title": m.get("title", manifest.parent.name),
            "declarations": m["declarations"],
            "modules": m["modules"],
            "lean": m["lean"],
            "generated": m["generated"],
            "checked": True if m.get("check") else None,
        })
    if not entries:
        raise SystemExit(f"no bundles under {root}")
    entries.sort(key=lambda e: e["slug"])
    (root / "projects.json").write_text(json.dumps(entries, indent=2))
    for e in entries:
        print(f"  {e['slug']}: {e['declarations']:,} declarations, {'re-checked' if e['checked'] else 'not re-checked'}")


if __name__ == "__main__":
    main(pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "site/data"))
